version: '3'

services:

  db:
    image: postgres
    container_name: my-postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${ADMIN}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${NAME}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my-network

  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - my-network

  web:
    build: .
    container_name: diplom
    command: bash -c "celery -A settings.celery worker --loglevel=info &\
     celery -A settings.celery beat --loglevel=info & \
     uvicorn settings.asgi:application --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://my-redis:6379/0
    restart: always
    networks:
      - my-network

  nginx:
    image: nginx
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/app/staticfiles/
      - ./media:/app/media/
    depends_on:
      - web
    restart: always
    networks:
      - my-network


networks:
  my-network: